version: 3
workdir: internal

components:
  bootstrap: { in: bootstrap }
  config: { in: config }
  dto: { in: dto/** }
  entity: { in: entity }
  handler: { in: handler }
  middleware: { in: middleware }
  migration: { in: migration }
  repository_registry: { in: repository }
  feature_repository: { in: repository/* }
  feature_repository_database: { in: repository/*/database }
  auth_repository: { in: repository/auth }
  auth_repository_redis: { in: repository/auth/redis }
  dbexecutor: { in: repository/dbexecutor }
  health_repository: { in: repository/health }
  health_repository_database: { in: repository/health/database }
  user_repository: { in: repository/user }
  user_repository_database: { in: repository/user/database }
  workspace_repository: { in: repository/workspace }
  workspace_repository_database: { in: repository/workspace/database }
  response: { in: response }
  router: { in: router }
  service: { in: service }
  utils: { in: utils }

vendors:
  cors: { in: github.com/gin-contrib/cors }
  gin: { in: github.com/gin-gonic/gin }
  pgconn: { in: github.com/jackc/pgx/v5/pgconn }
  pgx_stdlib: { in: github.com/jackc/pgx/v5/stdlib }
  redis: { in: github.com/redis/go-redis/v9 }
  bcrypt: { in: golang.org/x/crypto/bcrypt }
  sqlx: { in: github.com/jmoiron/sqlx }
  viper: { in: github.com/spf13/viper }
  zap: { in: go.uber.org/zap }

deps:
  bootstrap:
    mayDependOn:
      - config
    canUse:
      - pgx_stdlib
      - redis
      - sqlx
      - viper
      - zap

  config:
    canUse:
      - redis
      - sqlx

  router:
    mayDependOn:
      - handler
      - middleware
    canUse:
      - cors
      - gin
      - zap

  handler:
    mayDependOn:
      - dto
      - entity
      - response
      - service
      - utils
    canUse:
      - gin

  middleware:
    canUse:
      - gin
      - zap

  migration:
    canUse:
      - sqlx

  dbexecutor:
    canUse:
      - sqlx
      - zap

  service:
    mayDependOn:
      - auth_repository
      - entity
      - feature_repository
      - health_repository
      - repository_registry
      - user_repository
      - workspace_repository
    canUse:
      - bcrypt

  repository_registry:
    mayDependOn:
      - auth_repository
      - auth_repository_redis
      - config
      - dbexecutor
      - feature_repository
      - feature_repository_database
      - health_repository
      - health_repository_database
      - user_repository
      - user_repository_database
      - workspace_repository
      - workspace_repository_database

  health_repository_database:
    mayDependOn:
      - config
      - dbexecutor

  auth_repository_redis:
    mayDependOn:
      - auth_repository
    canUse:
      - redis

  feature_repository:
    mayDependOn:
      - entity

  feature_repository_database:
    mayDependOn:
      - config
      - dbexecutor
      - entity
      - feature_repository
    canUse:
      - pgconn

  user_repository:
    mayDependOn:
      - entity

  user_repository_database:
    mayDependOn:
      - config
      - dbexecutor
      - entity
      - user_repository
    canUse:
      - pgconn

  workspace_repository:
    mayDependOn:
      - entity

  workspace_repository_database:
    mayDependOn:
      - config
      - dbexecutor
      - entity
      - workspace_repository
    canUse:
      - pgconn

  response:
    canUse:
      - gin
